config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'top#index'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get 'login', to: 'user_sessions#new'
  post 'gest_login', to: 'user_sessions#gest_login'

  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'profile', to: 'profiles#edit'
  patch 'profile', to: 'profiles#update'

  resources :password_resets, only: %i[new create edit update]

  resources :insects, only: %i[index show] do
    resource :bookmarks, only: %i[create destroy]
    collection do
      get :bookmarks
    end
    resources :comments, only: %i[create destroy], shallow: true
  end

  get 'insect_questions', to: 'questions#questions'
  get 'results', to: 'questions#results'
end

app/models/insect.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: insects
#
#  id                     :bigint           not null, primary key
#  cooking_store_link     :text(65535)
#  insect_img             :string(255)
#  insect_recipe          :string(255)
#  introduction           :string(255)
#  name                   :string(255)
#  online_store_link      :text(65535)
#  video_appearance_scene :string(255)
#  video_url_link         :text(65535)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  insect_rank_id         :bigint           not null
#
# Indexes
#
#  index_insects_on_insect_rank_id  (insect_rank_id)
#
# Foreign Keys
#
#  fk_rails_...  (insect_rank_id => insect_ranks.id)
#
class Insect < ApplicationRecord
  mount_uploader :insect_img, InsectImgUploader
  has_many :graphs, dependent: :destroy # ⅰ、ⅱ
  has_many :bookmarks, dependent: :destroy # ⅰ、ⅱ
  has_many :comments, dependent: :destroy
  belongs_to :insect_rank
end

app/controllers/insects_controller.rb
# frozen_string_literal: true

class InsectsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]

  def index
    @q = Insect.ransack(params[:q])
    @insects = @q.result(distinct: true).page(params[:page]).per(6)
  end

  def show
    @insect = Insect.find(params[:id])
    gon.chart_data = @insect.graphs.pluck(:data)
    @comments = @insect.comments.includes(:user).order(created_at: :desc)
  end

  def bookmarks
    @q = current_user.bookmarks_insect.ransack(params[:q])
    @bookmarks_insect = @q.result(distinct: true).page(params[:page]).per(6)
  end
end

app/views/insects/_bookmark.html.slim
= link_to insect_bookmarks_path(insect_id: insect.id), id: "js-insect-#{insect.id}", method: :post, remote: true do
  i.fa-regular.fa-heart.text-danger.lead.d-block.pl-5.ml-3.ml-lg-2

app/views/insects/_bookmark_btn.html.slim
- if current_user.bookmark?(insect)
  = render 'un_bookmark', insect: insect
- else
  = render 'bookmark', insect: insect

app/views/insects/_comment.html.slim
tr id=("comment-#{comment.id}")
  td.comment-td-area
    = image_tag comment.user.avatar.url, class: 'rounded-circle', size: '50x50'
  td
    h3.small.text-left.mb-0.font-weight-bold.pt-0.pb-1= comment.user.name
    div id=("js-comment-#{comment.id}")
      p.mb-0 = comment.body

  td.d-flex.align-items-center.trash-icon.justify-content-center
    - if current_user.mine?(comment)
      = link_to insect_comment_path(comment), method: :delete, remote: true, data: { confirm: '本当に削除して良いですか?' }
        i.fa-solid.fa-trash-can

app/views/insects/_insect.html.slim
.my-lg-5.col-md-6.col-lg-4.my-4
  = link_to insect_path(insect), class:'text-decoration-none text-dark' do
    = image_tag insect.insect_img.url, class:'d-block mx-auto mb-3', width: '200', height: '150'
    p.mb-0.font-weight-bold.text-center = insect.name
  - if logged_in?
    = render 'bookmark_btn', insect: insect

app/views/insects/_un_bookmark.html.slim
= link_to insect_bookmarks_path(insect_id: insect.id), id: "js-insect-#{insect.id}", method: :delete, remote: true do
  i.fa-solid.fa-heart.text-danger.lead.d-block.pl-5.ml-3.ml-lg-2

app/views/insects/bookmarks.html.slim
- content_for(:title, t('.title'))

.m-4
  h3.text-left.title_padding_top = t('.title')
  = render 'shared/search', q: @q

  .row.mb-5
    - if @bookmarks_insect.any?
      = render @bookmarks_insect
    - else
      p.m-4 = t('.faborite_insect')

  = paginate @bookmarks_insect

app/views/insects/index.html.slim
- content_for(:title, t('.title'))

.m-4
  h3.text-left.title_padding_top = t('.title')
  = render 'shared/search', q: @q

  .row.mb-5
    - if @insects.any?
      = render @insects
    - else
      p.m-4 = t('.not_insect')

  = paginate @insects

app/views/insects/show.html.slim
- content_for(:title, t('.title'))

.m-4
  h3.text-left.title_padding_top = t('.title')

  = link_to t('.back_index_page'), insects_path, class: 'nav-link text-muted'
  .row
    .col-lg-6
      = image_tag @insect.insect_img.url, class:'d-block mx-auto mb-3 pt-5', width: '350'
    = Gon::Base.render_data
    .col-lg-6
      canvas#myChart
  .row.mt-3
    .col-lg-6.mb-3.mb-lg-5
      h3.text-left.mb-3.mb-lg-5  = t('.introduction')
      table.table.w-100.border-none.table-pc
        tbody
          tr
            th.small.font-weight-bold = t('.name')
            td.small.font-weight-bold = @insect.name
          tr
            th.small.font-weight-bold = t('.insect_introduction')
            td.small.font-weight-bold = @insect.introduction
          tr
            th.small.font-weight-bold = t('.eat_store')
            td.small.font-weight-bold = @insect.cooking_store_link.nil? ?  '調査中' : text_url_to_link(h(@insect.cooking_store_link)).html_safe
          tr
            th.small.font-weight-bold = t('.insect_recipe')
            td.small.font-weight-bold =  @insect.insect_recipe.nil? ?  '調査中' : text_url_to_link(h(@insect.insect_recipe)).html_safe
          tr.border-bottom
            th.font-weight-bold = t('.only_store')
            td.small.font-weight-bold = @insect.online_store_link.nil? ?  '調査中' : text_url_to_link(h(@insect.online_store_link)).html_safe
          p.small = t('.not_insect_store')

      .d-lg-none
        p.mb-2 = t('.name')
        p.font-weight-bold.border-bottom = @insect.name
        p.mb-2 = t('.insect_introduction')
        p.font-weight-bold.border-bottom = @insect.introduction
        p.mb-2 = t('.insect_recipe')
        p.font-weight-bold.border-bottom =  @insect.insect_recipe.nil? ?  '調査中' : text_url_to_link(h(@insect.insect_recipe)).html_safe
        p.mb-2 = t('.eat_store')
        p.font-weight-bold.border-bottom =  @insect.cooking_store_link.nil? ?  '調査中' : text_url_to_link(h(@insect.cooking_store_link)).html_safe
        p.mb-2 = t('.only_store')
        p.font-weight-bold.border-bottom =  @insect.online_store_link.nil? ?  '調査中' : text_url_to_link(h(@insect.online_store_link)).html_safe

    .col-lg-6
      h3.text-left.mb-3.mb-lg-5 = t('.reference_movie')
      .text-center.mb-3
        iframe allow=("accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture") allowfullscreen="" frameborder="0" height="255" src=("https://www.youtube.com/embed/#{@insect.video_url_link}") width="400"
        p.mb-0 = t('.video_appearance_scene')
        p = @insect.video_appearance_scene

  .mx-lg-5.px-lg-5
    .w-100.mx-auto
      h3.text-left.mb-3.mb-lg-5.p-0  = t('.comments')
      = render 'comments/form', insect: @insect, comment: @insect.comments.build
      = render 'comments/comments', comments: @comments