config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'top#index'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get 'login', to: 'user_sessions#new'
  post 'gest_login', to: 'user_sessions#gest_login'

  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'profile', to: 'profiles#edit'
  patch 'profile', to: 'profiles#update'

  resources :password_resets, only: %i[new create edit update]

  resources :insects, only: %i[index show] do
    resource :bookmarks, only: %i[create destroy]
    collection do
      get :bookmarks
    end
    resources :comments, only: %i[create destroy], shallow: true
  end

  get 'insect_questions', to: 'questions#questions'
  get 'results', to: 'questions#results'
end

app/views/shared/_before_login_nav.html.slim
= link_to sign_up_path, class: 'text-light text-decoration-none d-block mb-3 mb-lg-0 mx-lg-3' do
  '新規登録
  span.text-light.fa-solid.fa-pen.ml-2.icon-margin
= link_to login_path, class: 'text-light text-decoration-none d-block mb-3 mb-lg-0' do
  'ログイン
  span.text-light.icon-margin.fas.fa-sign-in-alt.mr-3
= link_to gest_login_path, method: :post, class: 'text-light text-decoration-none d-block mb-3 mb-lg-0' do
  'ゲストログイン
  span.text-light.icon-margin.fa-solid.fa-user

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
  = content_tag :div, message, class: "alert alert-#{message_type}", id: 'flash'

app/views/shared/_footer.html.slim
footer.py-2.py-lg-4.px-lg-5
  .d-lg-flex.justify-content-between.pc-size
    .
      = link_to t('defaults.footer_terms'), terms_path, class: 'navbar-brand text-light mx-3'
      = link_to t('defaults.footer_poricy'), privacy_path, class: 'navbar-brand text-light'
      = link_to t('defaults.footer_contact'), 'https://docs.google.com/forms/d/e/1FAIpQLScQwylK4RiiSoOLDsVChL6B8u4Io2rLOovMsu2O0z9xJYojQQ/viewform', class: 'navbar-brand text-light mr-4'
      = link_to "https://twitter.com/share?&url=https://insect-food.jp/&text=%0D%0A食べれる昆虫を検索・診断の結果で自分に合った昆虫を探せるサービス&hashtags=昆虫,昆虫食,ゲテモノ,個人開発&lang=ja", title: 'Twitter', target: :_blank, rel: 'noopener noreferrer', class: 'text-white twitter-icon'
        i.fab.fa-twitter
    .copy-ligth
      p.text-white.mb-0 &copy; 2022 insect-food
  p.text-white.mb-0.text-center.m-3.d-lg-none &copy; 2022 insect-food

app/views/shared/_hamberger.html.slim
div#drawer_toggle.d-lg-none
  span
  span
  span

app/views/shared/_hamberger_on_list.html.slim
div#toggle-nav.d-lg-none
  .inner.py-5.my-5.mx-5.px-4.text-left
    = link_to insects_path, class: 'text-decoration-none d-block text-light mb-3' do
      '食べれる虫一覧
      span.text-lg-light.fa-solid.fa-utensils.icon-margin
    - if logged_in?
      = render 'shared/login_nav'
    - else
      = render 'shared/before_login_nav'
    = link_to terms_path, class: 'text-decoration-none d-block text-light mb-3' do
      '利用規約
    = link_to privacy_path, class: 'text-decoration-none d-block text-light mb-3' do
      'プライバシーポリシー
    = link_to t('defaults.footer_contact'), 'https://docs.google.com/forms/d/e/1FAIpQLScQwylK4RiiSoOLDsVChL6B8u4Io2rLOovMsu2O0z9xJYojQQ/viewform', class: 'navbar-brand text-light mb-3 mb-lg-0 d-block p-0 praibasce'
    = link_to "https://twitter.com/share?&url=https://insect-food.jp/&text=%0D%0A食べれる昆虫を検索・診断の結果で自分に合った昆虫を探せるサービス&hashtags=昆虫,昆虫食,ゲテモノ,個人開発&lang=ja", title: 'Twitter', target: :_blank, rel: 'noopener noreferrer', class: 'text-white twitter-icon'
        i.fab.fa-twitter

app/views/shared/_head.html.slim
head
  title
    = full_title(yield(:title))
  meta[name="viewport" content="width=device-width,initial-scale=1"]
  = display_meta_tags(default_meta_tags)
  = csrf_meta_tags
  = csp_meta_tag
  script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  = favicon_link_tag('favicon.ico')
  - if Rails.env.production?
    = render 'layouts/google_analytics'

app/views/shared/_login_nav.html.slim
= link_to bookmarks_insects_path, class: 'text-light text-decoration-none d-block mb-3 mb-lg-0 mx-lg-3' do
  'お気に入りした虫一覧
  span.text-light.icon-margin.fa-solid.fa-heart
= link_to profile_path, class: 'text-light text-decoration-none mr-4 d-block mb-lg-0 mb-3' do
  = current_user.name
= link_to logout_path, method: :delete, class: 'text-light text-decoration-none d-block mb-lg-0 mb-3' do
  'ログアウト
  span.text-light.icon-margin.fas.fa-sign-in-alt

app/views/shared/_navbar.html.slim
nav.nav-bgc.navbar.text-light.px-lg-5.py-lg-3.navbar-fixed
  .container-fluid
    = link_to 'Insect Food', root_path, class: 'navbar-brand text-light'
    = render 'shared/hamberger_on_list'
    .nav-menu.d-lg-flex.d-none.d-lg-block
      = link_to insects_path, class: 'text-light text-decoration-none' do
        '食べれる虫一覧
        span.text-light.fa-solid.fa-utensils.icon-margin.ml-2
      - if logged_in?
        = render 'shared/login_nav'
      - else
        = render 'shared/before_login_nav'
    = render 'shared/hamberger'

app/views/shared/_search.html.slim
= search_form_for q do |f|
  .form-group
    .d-flex
      = f.search_field :name_cont, class: 'form-control w-75', placeholder: t('defaults.search_insects'), id: 'search_eria'
      .form-group
        = f.submit class: 'btn btn-primary ml-3'

app/views/shared/_top_header.html.slim
header
  .top-header.text-light
    .header-fixed#header-fixed
      = render 'shared/top_navbar'
    = render 'shared/flash_message'
    .row
      .text-center.col-lg-6
      .header-text.col-12.col-lg-6.text-center.p-4
        h3.mb-3.sm-h3-size = t('defaults.header_title')
        p.mb-1.sm-font-size = t('defaults.header_p1')
        p.m-0.sm-font-size = t('defaults.header_p2')

app/views/shared/_top_navbar.html.slim
nav.navbar.navbar-light.text-light.px-lg-5.py-lg-3
  .container-fluid
    = link_to 'Insect Food', root_path, class: 'navbar-brand text-light'
    = render 'shared/hamberger_on_list'
    .nav-menu.d-lg-flex.d-none.d-lg-block
      = link_to insects_path, class: 'text-light text-decoration-none' do
        '食べれる虫一覧
        span.text-light.fa-solid.fa-utensils.icon-margin
      - if logged_in?
        = render 'shared/login_nav'
      - else
        = render 'shared/before_login_nav'
    = render 'shared/hamberger'