config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'top#index'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get 'login', to: 'user_sessions#new'
  post 'gest_login', to: 'user_sessions#gest_login'

  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'profile', to: 'profiles#edit'
  patch 'profile', to: 'profiles#update'

  resources :password_resets, only: %i[new create edit update]

  resources :insects, only: %i[index show] do
    resource :bookmarks, only: %i[create destroy]
    collection do
      get :bookmarks
    end
    resources :comments, only: %i[create destroy], shallow: true
  end

  get 'insect_questions', to: 'questions#questions'
  get 'results', to: 'questions#results'
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create gest_login]
  before_action :logged_in_user, only: %i[new]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_url, success: t('controller.success_login')
    else
      flash.now[:danger] = t('controller.not_login')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, success: t('controller.logout')
  end

  def gest_login
    @guest_user = User.create(
      name: "テストユーザー#{SecureRandom.alphanumeric(6)}",
      email: "#{SecureRandom.alphanumeric(10)}@email.com",
      password: 'password',
      password_confirmation: 'password'
    )
    auto_login(@guest_user)
    redirect_to root_url, success: t('controller.gest_login')
  end

  private

  def logged_in_user
    redirect_to root_url, danger: t('controller.logged_in_user') if logged_in?
  end
end

app/views/user_sessions/new.html.slim
- content_for(:title, t('.login'))

.form_padding_top
  .mx-3
    .form-wrapper
      h3.form_title = t('.login')
      = form_with url: login_path, method: :post do |f|
        .form-item
          = f.text_field :email, placeholder: t('.mail'), required: true
        .form-item
          = f.password_field :password, placeholder: t('.password'), required: true
        .button-panel
          = f.submit t('.login'), class: 'submit-btn'
      .form-footer.p-3
        p.mt-3
          = link_to t('.create'), sign_up_path
        p.mb-0
          = link_to t('.resets_password'), new_password_reset_path